In [1]:
import pandas as pd

customers = pd.read_csv("./Dataset/customers.csv")
products = pd.read_csv("./Dataset/products.csv")
sales = pd.read_csv("./Dataset/sales.csv")

In [2]:
customers

  CustomerID CustomerName      City
0       C101        Alice  New York
1       C102          Bob   Chicago
2       C103      Charlie    Dallas
3       C104        Diana   Seattle

In [3]:
products

  ProductID ProductName  Price
0      P101      Laptop  50000
1      P102       Mouse    800
2      P103    Keyboard   1500
3      P104     Monitor  12000

In [4]:
sales

  SaleID CustomerID ProductID  Quantity
0   S001       C101      P101         1
1   S002       C102      P102         3
2   S003       C103      P103         2
3   S004       C104      P104         1
4   S005       C101      P102         5

In [5]:
sales_product = sales.merge(products, on="ProductID")